development:
  dialect: postgres
  datasource: dbname=work user=root password=password sslmode=disable
  dir: _db/migrate
  table: migrations

test:
  dialect: postgres
  datasource: dbname=work_test user=root sslmode=disable
  dir: _db/migrate
  table: migrations
