---
apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: sample
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: asia.gcr.io/dev-oshou02/awesome-music-api
    context: .
    docker:
      dockerfile: ./deployments/Dockerfile
