version: 2.1
executors:
  default:
    working_directory: /go/src/github.com/oshou/Awesomemusic-api
    docker:
      - image: circleci/golang:latest
commands:
  deploy_hub:
    steps:
      - run:
          name: Deploy Docker Registry
          command: make deploy_hub
  install_golangci_lint:
    steps:
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.8
      - run:
          name: Add Path
          command: echo 'export PATH=$PATH:/go/src/github.com/oshou/Awesomemusic-api/bin' >> $BASH_ENV
      - run:
          name: Reload
          command: source $BASH_ENV
jobs:
  deploy_prd:
    executor: default
    steps:
      - checkout
      - install_golangci_lint
      - setup_remote_docker
      - deploy_hub
  deploy_dev:
    executor: default
    steps:
      - checkout
      - install_golangci_lint
      - setup_remote_docker
      - deploy_hub
  deploy_test:
    executor: default
    steps:
      - checkout
      - install_golangci_lint
      - setup_remote_docker
      - deploy_hub

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy_prd:
          filters:
            branches:
              only: master
      - deploy_dev:
          filters:
            branches:
              only: develop
      - deploy_test:
          filters:
            branches:
              only: feature/modify_ci_logic
