version: 2.1
executors:
  default:
    working_directory: /go/src/github.com/oshou/Awesomemusic-api
    docker:
      - image: circleci/golang:latest
commands:
  deploy_hub:
    steps:
      - run:
          name: Deploy Docker Registry
          command: make deploy_hub
  install_golangci_lint:
    steps:
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.23.8
      - run:
          name: Add Path
          command: export PATH=$PATH:/usr/local/bin
      - run:
          name: reload
          command: source ~/.bashrc
jobs:
  deploy_prd:
    executor: default
    steps:
      - checkout
      - install_golangci_lint
      - deploy_hub
  deploy_test:
    executor: default
    steps:
      - checkout
      - install_golangci_lint
      - deploy_hub

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy_prd:
          filters:
            branches:
              only: master
      - deploy_test:
          filters:
            branches:
              only: feature/deploy-test
