version: "2.1"

commands:
  deply_hub:
    steps:
      - run:
          name: Deploy Docker Registry
          command: make deploy_hub

jobs:
  deploy_prd:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - deploy_hub
  deploy_test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - deploy_hub

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy_prd:
          filters:
            branches:
              only: master
      - deploy_test:
          filters:
            branches:
              only: feature/test
