version: 2.1
command:
  deploy_hub:
    steps:
      - run:
          name: Deploy Docker Registry
          command: make deploy_hub
  install_golangci_lint:
    steps:
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.8

jobs:
  deploy_prd:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - install_golangci_lint
      - make deploy_hub
  deploy_test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - install_golangci_lint
      - make deploy_hub

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy_prd:
        filters:
          branches:
            only: master
      - deploy_test:
        filters:
          branches:
            only: feature/deploy-test
