// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/post.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/oshou/AwesomeMusic-api/domain/model"
	reflect "reflect"
)

// MockIPostUsecase is a mock of IPostUsecase interface
type MockIPostUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIPostUsecaseMockRecorder
}

// MockIPostUsecaseMockRecorder is the mock recorder for MockIPostUsecase
type MockIPostUsecaseMockRecorder struct {
	mock *MockIPostUsecase
}

// NewMockIPostUsecase creates a new mock instance
func NewMockIPostUsecase(ctrl *gomock.Controller) *MockIPostUsecase {
	mock := &MockIPostUsecase{ctrl: ctrl}
	mock.recorder = &MockIPostUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPostUsecase) EXPECT() *MockIPostUsecaseMockRecorder {
	return m.recorder
}

// GetPosts mocks base method
func (m *MockIPostUsecase) GetPosts() ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts")
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts
func (mr *MockIPostUsecaseMockRecorder) GetPosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockIPostUsecase)(nil).GetPosts))
}

// GetPostByID mocks base method
func (m *MockIPostUsecase) GetPostByID(postID int) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByID", postID)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByID indicates an expected call of GetPostByID
func (mr *MockIPostUsecaseMockRecorder) GetPostByID(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByID", reflect.TypeOf((*MockIPostUsecase)(nil).GetPostByID), postID)
}

// GetPostsByTagID mocks base method
func (m *MockIPostUsecase) GetPostsByTagID(tagID int) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByTagID", tagID)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByTagID indicates an expected call of GetPostsByTagID
func (mr *MockIPostUsecaseMockRecorder) GetPostsByTagID(tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByTagID", reflect.TypeOf((*MockIPostUsecase)(nil).GetPostsByTagID), tagID)
}

// GetPostsByUserID mocks base method
func (m *MockIPostUsecase) GetPostsByUserID(userID int) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByUserID", userID)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByUserID indicates an expected call of GetPostsByUserID
func (mr *MockIPostUsecaseMockRecorder) GetPostsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByUserID", reflect.TypeOf((*MockIPostUsecase)(nil).GetPostsByUserID), userID)
}

// AddPost mocks base method
func (m *MockIPostUsecase) AddPost(userID int, title, url, message string) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPost", userID, title, url, message)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPost indicates an expected call of AddPost
func (mr *MockIPostUsecaseMockRecorder) AddPost(userID, title, url, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPost", reflect.TypeOf((*MockIPostUsecase)(nil).AddPost), userID, title, url, message)
}

// DeletePostByID mocks base method
func (m *MockIPostUsecase) DeletePostByID(postID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostByID", postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostByID indicates an expected call of DeletePostByID
func (mr *MockIPostUsecaseMockRecorder) DeletePostByID(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostByID", reflect.TypeOf((*MockIPostUsecase)(nil).DeletePostByID), postID)
}
