// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/search.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/oshou/AwesomeMusic-api/domain/model"
	reflect "reflect"
)

// MockISearchUsecase is a mock of ISearchUsecase interface
type MockISearchUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockISearchUsecaseMockRecorder
}

// MockISearchUsecaseMockRecorder is the mock recorder for MockISearchUsecase
type MockISearchUsecaseMockRecorder struct {
	mock *MockISearchUsecase
}

// NewMockISearchUsecase creates a new mock instance
func NewMockISearchUsecase(ctrl *gomock.Controller) *MockISearchUsecase {
	mock := &MockISearchUsecase{ctrl: ctrl}
	mock.recorder = &MockISearchUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockISearchUsecase) EXPECT() *MockISearchUsecaseMockRecorder {
	return m.recorder
}

// GetPostsByTitle mocks base method
func (m *MockISearchUsecase) GetPostsByTitle(q string) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByTitle", q)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByTitle indicates an expected call of GetPostsByTitle
func (mr *MockISearchUsecaseMockRecorder) GetPostsByTitle(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByTitle", reflect.TypeOf((*MockISearchUsecase)(nil).GetPostsByTitle), q)
}

// GetPostsByUserName mocks base method
func (m *MockISearchUsecase) GetPostsByUserName(q string) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByUserName", q)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByUserName indicates an expected call of GetPostsByUserName
func (mr *MockISearchUsecaseMockRecorder) GetPostsByUserName(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByUserName", reflect.TypeOf((*MockISearchUsecase)(nil).GetPostsByUserName), q)
}

// GetPostsByTagName mocks base method
func (m *MockISearchUsecase) GetPostsByTagName(q string) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByTagName", q)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByTagName indicates an expected call of GetPostsByTagName
func (mr *MockISearchUsecaseMockRecorder) GetPostsByTagName(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByTagName", reflect.TypeOf((*MockISearchUsecase)(nil).GetPostsByTagName), q)
}
