// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/tag.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/oshou/AwesomeMusic-api/api/domain/model"
	reflect "reflect"
)

// MockITagUsecase is a mock of ITagUsecase interface
type MockITagUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockITagUsecaseMockRecorder
}

// MockITagUsecaseMockRecorder is the mock recorder for MockITagUsecase
type MockITagUsecaseMockRecorder struct {
	mock *MockITagUsecase
}

// NewMockITagUsecase creates a new mock instance
func NewMockITagUsecase(ctrl *gomock.Controller) *MockITagUsecase {
	mock := &MockITagUsecase{ctrl: ctrl}
	mock.recorder = &MockITagUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockITagUsecase) EXPECT() *MockITagUsecaseMockRecorder {
	return m.recorder
}

// GetTags mocks base method
func (m *MockITagUsecase) GetTags() ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags")
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags
func (mr *MockITagUsecaseMockRecorder) GetTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockITagUsecase)(nil).GetTags))
}

// GetTagByID mocks base method
func (m *MockITagUsecase) GetTagByID(tagID int) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByID", tagID)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByID indicates an expected call of GetTagByID
func (mr *MockITagUsecaseMockRecorder) GetTagByID(tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByID", reflect.TypeOf((*MockITagUsecase)(nil).GetTagByID), tagID)
}

// GetTagsByPostID mocks base method
func (m *MockITagUsecase) GetTagsByPostID(postID int) ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByPostID", postID)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByPostID indicates an expected call of GetTagsByPostID
func (mr *MockITagUsecaseMockRecorder) GetTagsByPostID(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByPostID", reflect.TypeOf((*MockITagUsecase)(nil).GetTagsByPostID), postID)
}

// AddTag mocks base method
func (m *MockITagUsecase) AddTag(tagName string) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", tagName)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTag indicates an expected call of AddTag
func (mr *MockITagUsecaseMockRecorder) AddTag(tagName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockITagUsecase)(nil).AddTag), tagName)
}

// AttachTag mocks base method
func (m *MockITagUsecase) AttachTag(postID, tagID int) (*model.PostTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachTag", postID, tagID)
	ret0, _ := ret[0].(*model.PostTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachTag indicates an expected call of AttachTag
func (mr *MockITagUsecaseMockRecorder) AttachTag(postID, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachTag", reflect.TypeOf((*MockITagUsecase)(nil).AttachTag), postID, tagID)
}
