// Code generated by MockGen. DO NOT EDIT.
// Source: search.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/oshou/AwesomeMusic-api/api/domain/model"
	reflect "reflect"
)

// MockISearchRepository is a mock of ISearchRepository interface
type MockISearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISearchRepositoryMockRecorder
}

// MockISearchRepositoryMockRecorder is the mock recorder for MockISearchRepository
type MockISearchRepositoryMockRecorder struct {
	mock *MockISearchRepository
}

// NewMockISearchRepository creates a new mock instance
func NewMockISearchRepository(ctrl *gomock.Controller) *MockISearchRepository {
	mock := &MockISearchRepository{ctrl: ctrl}
	mock.recorder = &MockISearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockISearchRepository) EXPECT() *MockISearchRepositoryMockRecorder {
	return m.recorder
}

// ListByTitle mocks base method
func (m *MockISearchRepository) ListByTitle(q string) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTitle", q)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTitle indicates an expected call of ListByTitle
func (mr *MockISearchRepositoryMockRecorder) ListByTitle(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTitle", reflect.TypeOf((*MockISearchRepository)(nil).ListByTitle), q)
}

// ListByUserName mocks base method
func (m *MockISearchRepository) ListByUserName(q string) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserName", q)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserName indicates an expected call of ListByUserName
func (mr *MockISearchRepositoryMockRecorder) ListByUserName(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserName", reflect.TypeOf((*MockISearchRepository)(nil).ListByUserName), q)
}

// ListByTagName mocks base method
func (m *MockISearchRepository) ListByTagName(q string) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTagName", q)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTagName indicates an expected call of ListByTagName
func (mr *MockISearchRepositoryMockRecorder) ListByTagName(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTagName", reflect.TypeOf((*MockISearchRepository)(nil).ListByTagName), q)
}
