development:
  dialect: postgres
  datasource: dbname=postgres user=root password=password sslmode=disable
  dir: _db/migrate
  table: migrations

test:
  dialect: postgres
  datasource: dbname=postgres_test user=root sslmode=disable
  dir: _db/migrate
  table: migrations
