/*
 * AwesomeMusic API
 *
 * 音楽サービス AwesomeMusicのWebAPI
 *
 * API version: 0.0.1
 * Contact: adf1985adf@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
)

// AddComment -
func AddComment(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// AddPost -
func AddPost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// DeleteComment -
func DeleteComment(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// DeletePost -
func DeletePost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// GetComment -
func GetComment(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	comments := Comment{
		Id:   1,
		message: "初めて聴きましたが良い曲でした"
	}
	json.NewEncoder(w).Encode(comment)
}

// GetComments -
func GetComments(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	comments := []Comment{
		{
			Id:   1,
			message: "初めて聴きましたが良い曲でした"
		},
		{
			Id:   2,
			message: "秋に来日するらしいので絶対ライブ行きます！"
		},
	}
	json.NewEncoder(w).Encode(comments)
}

// GetPost -
func GetPost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	post := Post{
		Id:   1,
		url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
		message: "夏に聴きたい1曲"
	}
	json.NewEncoder(w).Encode(post)
}

// GetPosts -
func GetPosts(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	posts := []Post{
		{
			Id:   1,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
		{
			Id:   2,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
	}
	json.NewEncoder(w).Encode(posts)
}

// GetTags -
func GetTags(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	tags := []Tag{
		{
			Id:   1,
			Name: "2019年",
		},
		{
			Id:   2,
			Name: "ロック",
		},
	}
	json.NewEncoder(w).Encode(tags)
}

// GetUsers -
func GetUsers(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	users := []User{
		{
			Id:   1,
			Name: "kawauso",
		},
		{
			Id:   2,
			Name: "kawauso-kun",
		},
	}
	json.NewEncoder(w).Encode(users)
}

// SearchByPosts -
func SearchByPosts(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	posts := []Post{
		{
			Id:   1,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
		{
			Id:   2,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
	}
	json.NewEncoder(w).Encode(posts)
}

// SearchByTags -
func SearchByTags(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	posts := []Post{
		{
			Id:   1,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
		{
			Id:   2,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
	}
	json.NewEncoder(w).Encode(posts)
}

// SearchByUsers -
func SearchByUsers(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	posts := []Post{
		{
			Id:   1,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
		{
			Id:   2,
			url: "https://www.youtube.com/watch?v=gbx55BK-6_4"
			message: "夏に聴きたい1曲"
		},
	}
	json.NewEncoder(w).Encode(posts)
}
