/*
 * AwesomeMusic API
 *
 * 音楽サービス AwesomeMusicのWebAPI
 *
 * API version: 0.0.1
 * Contact: adf1985adf@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	{
		"AddComment",
		strings.ToUpper("Post"),
		"/v1/posts/{post_id}/comments",
		AddComment,
	},

	{
		"AddPost",
		strings.ToUpper("Post"),
		"/v1/posts",
		AddPost,
	},

	{
		"DeleteComment",
		strings.ToUpper("Delete"),
		"/v1/posts/{post_id}/comments/{comment_id}",
		DeleteComment,
	},

	{
		"DeletePost",
		strings.ToUpper("Delete"),
		"/v1/posts/{post_id}",
		DeletePost,
	},

	{
		"GetComment",
		strings.ToUpper("Get"),
		"/v1/posts/{post_id}/comments/{comment_id}",
		GetComment,
	},

	{
		"GetComments",
		strings.ToUpper("Get"),
		"/v1/posts/{post_id}/comments",
		GetComments,
	},

	{
		"GetPost",
		strings.ToUpper("Get"),
		"/v1/posts/{post_id}",
		GetPost,
	},

	{
		"GetPosts",
		strings.ToUpper("Get"),
		"/v1/posts",
		GetPosts,
	},

	{
		"GetTags",
		strings.ToUpper("Get"),
		"/v1/tags",
		GetTags,
	},

	{
		"GetUsers",
		strings.ToUpper("Get"),
		"/v1/users",
		GetUsers,
	},

	{
		"SearchByType",
		strings.ToUpper("Get"),
		"/v1/search",
		SearchByType,
	},
}
