@startuml
package Domain(業務ロジック) {
  class Model
  interface IRepository
}
package Usecase(アプリケーションロジック) {
  class Usecase
  interface IUsecase
  interface IPorts
}

package adapter {
  package Infrastructure {
    class Datastore
    class Adapters
  }
  package Presentor {
    class Router
    interface IHandler
    class Handler
  }
}

Model <-right- IRepository
IUsecase -up-> IRepository
IUsecase -right-> IPorts
Usecase -right-> IUsecase: DI
IHandler -up-> IUsecase
Handler -> IHandler: DI
Router -up-> IHandler
Datastore -up-> IRepository: DI
Adapters -up-> IPorts: DI
@enduml
