@startuml
package Domain(業務ロジック) {
  class Model << DomainModel >>
  interface IRepository << DataAccess >>
}
package Usecase(アプリケーションロジック) {
  class Usecase
  interface IUsecase
}

package adapter {
  package Infrastructure {
    class Datastore
  }
  package Presentor {
    class Router
    class Middleware
    interface IHandler
    class Handler
  }
}

package cmd {
  class EntryPoint
}

Model <-right- IRepository
IUsecase -up-> IRepository
Usecase -right-> IUsecase: DI
IHandler -up-> IUsecase
Handler -right-> IHandler: DI
Router -up-> IHandler
Datastore -up-> IRepository: DI
EntryPoint -up-> Router
EntryPoint -up-> Middleware
@enduml
