@startuml
package Domain(業務ロジック) {
  class Model
  interface IRepository
}
package Usecase(アプリケーションロジック) {
  class Usecase
  interface IUsecase
  interface IInput
  interface IOutput
}

package ui {
  class Presenter
  class Handler
}
package Infrastructure {
  class Datastore
}

Model <-left- IRepository
IUsecase -up-> IRepository
IUsecase -left-> IInput
IUsecase -right-> IOutput
Usecase -right-> IUsecase: DI
Datastore -up-> IRepository: DI
Handler -up-> IInput: DI
Presenter -up-> IOutput: DI
@enduml
