```plantuml
@startuml
box "interface" #LightBlue
  participant server
  participant controller
end box
box "usecase" #Yellow
  participant usecase
end box
box "domain" #Pink
  participant service
  participant repository
  participant domain
end box

activate server
server -> server: APIサーバ起動
server -> server: 環境変数読み込み
server -> server: DBコネクション生成
server -> server: CQRSポリシー設定
[-> server :request
server -> controller: routing
controller -> controller: request解釈
controller -> service: service呼出
service -> repository: CRUD呼出
repository -> domain:
domain -> repository:
repository -> service: 呼出結果返却
service -> controller: 呼出結果返却
controller -> controller: response生成
controller -> server: response
@enduml
```

```plantuml
@startuml
activate server
server -> server: APIサーバ起動
server -> server: 環境変数読み込み
server -> server: DBコネクション生成
server -> server: CQRSポリシー設定
[-> server :request
server -> controller: routing
controller -> controller: requestパラメータ解釈
controller -> service: serviceを実行
service -> service: ビジネスロジック前処理
service -> DB: modelメソッドを実行
DB -> service: 処理結果返却
service -> service: ビジネスロジック後処理
service -> controller: 処理結果返却
controller-> controller: responseデータ生成
controller-> server: response
server ->[: response
@enduml
```
