@startuml
left to right direction
:APIクライアント:
rectangle User {
  APIクライアント --> (Add User)
  APIクライアント --> (Get UserList)
  APIクライアント --> (Get UserLista)
}
rectangle Post {
  APIクライアント --> (Add Post)
  APIクライアント --> (Get PostList)
  APIクライアント --> (Get PostLista)
}
@enduml
