@startuml
package DomainModel {
  class Model
}

package DomainService {
  interface IRepository
}

package Application {
  class Service
  interface IService
}

package Infrastructure {
  class Datastore
}
package UI {
  interface IRouter
  class Router
  class Middleware
  interface IHandler
  class Handler
}
class main

Model <-up- IRepository
IService -up-> IRepository
Datastore -up-> IRepository: DI
Service -right-> IService: DI
IHandler -up-> IService
Handler -right-> IHandler: DI
Router -up-> IHandler
Router -up-> Middleware
IRouter -up-> Router
main -up-> IRouter
@enduml
