@startuml
package DomainModel {
  class Model
}

package DomainService {
  interface IRepository
}

package Application {
  class Usecase
  interface IUsecase
}

package Infra {
  class Persistence
}
package UI {
  class Router
  class Middleware
  interface IHandler
  class Handler
}
class main

Model <-up- IRepository
IUsecase -up-> IRepository
Persistence -up-> IRepository: DI
Usecase -right-> IUsecase: DI
IHandler -up-> IUsecase
Handler -right-> IHandler: DI
Middleware -up-> IHandler
Router -up-> Middleware
main -up-> Router
@enduml
