```plantuml
@startuml
participant main
box "UI" #LightBlue
  participant router
  participant handler
end box
box "Application" #Yellow
  participant service
end box
box "Domain" #Orange
  participant repository
  participant model
end box
box "Infrastructure" #Gray
  participant persistence
end box

main -> main: Set Environment
main -> main: Set DBConnection
main -> main: DI
persistence -> repository: DI
main -> router: Start Server
activate router
router -> router: Set Middleware(Authentication)
router -> router: Set Middleware(CSRF Protection)
router -> router: Set Middleware(CORS Policy)
router -> router: Set Middleware(Rate Limit)
[-> router : Request
router -> handler: Routing
activate handler
handler -> handler: Parse Request
handler -> service: Call service
activate service
service -> service: PreTask(Transaction..etc)
service -> repository: Call Domain-Logic
activate repository
repository -> model: CRUD
repository <-- model:
deactivate repository
service <-- repository:
service -> repository: Call Domain-Logic
activate repository
repository -> model: CRUD
repository <-- model:
deactivate repository
service <-- repository:
service -> repository: Call Domain-Logic
activate repository
repository -> model: CRUD
repository <-- model:
deactivate repository
service <-- repository:
service -> service: PostTask(Transaction..etc)
deactivate service
handler <-- service:
handler -> handler: Create Response
router <- handler: Response
deactivate handler
[<- router: Response
@enduml
```
