```plantuml
@startuml
actor client
participant main
box "UI" #LightBlue
  participant router
  participant handler
end box
box "Application" #Yellow
  participant usecase
end box
box "Domain" #Orange
  participant repository
  participant model
end box
box "Infrastructure" #Gray
  participant persistence
end box

main -> main: Set Logger
main -> main: Set Config
main -> main: Set DBConnection
main -> main: Set SessionStore
main -> main: DI
persistence -> repository: DI
main -> router: Start Server
activate router
router -> router: Set Middleware(Authentication)
router -> router: Set Middleware(CORS Policy)
router -> router: Set Middleware(Rate Limit)
router -> router: Set Router
client -> router : HTTP Request
router -> handler: Routing
activate handler
handler -> handler: Parse HTTP Request
handler -> usecase: Call usecase
activate usecase
usecase -> usecase: PreTask(Transaction..etc)
usecase -> repository: Call Domain-Logic
activate repository
repository -> model: CRUD
repository <-- model:
deactivate repository
usecase <-- repository:
usecase -> repository: Call Domain-Logic
activate repository
repository -> model: CRUD
repository <-- model:
deactivate repository
usecase <-- repository:
usecase -> repository: Call Domain-Logic
activate repository
repository -> model: CRUD
repository <-- model:
deactivate repository
usecase <-- repository:
usecase -> usecase: PostTask(Transaction..etc)
deactivate usecase
handler <-- usecase:
handler -> handler: Create HTTP Response
client <- handler: HTTP Response
deactivate handler
@enduml
```
