@startuml
left to right direction
:APIClient:
rectangle User {
  APIClient --> (Login)
  APIClient --> (Logout)
  APIClient --> (List Users)
  APIClient --> (Get User by ID)
  APIClient --> (Add User)
}
rectangle Post {
  APIClient --> (List Posts)
  APIClient --> (Add Post)
  APIClient --> (Add PostComment)
  APIClient --> (List PostComment)
}
rectangle Tag {
  APIClient --> (List Tags)
  APIClient --> (Add Tag)
}
@enduml
