version: "2"
services:
  pg:
    container_name: postgres
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      LANG: ja_JP.utf8
    volumes:
      - ./volume/db/postgres:/var/lib/postgresql/data
    user: root
    restart: always
    working_dir: /var/lib/postgresql/data
