name: Delivery

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup gcloud sdk
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      - name:
      - run: gcloud auth configure-docker --quiet
      - run: make deploy
      - run: docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/sueken:${GITHUB_SHA::7} ./canary
      - run: docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/sueken:${GITHUB_SHA::7}
      - name: Install lint
        run: curl -sSfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
      - name: Lint
        run: make lint
      - name: Test
        run: make test
