name: develop

on:
  push:
    branches:
      - develop
      - feature/ci_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Install lint
        run: curl -sSfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
      - name: check2
        run: sudo pwd
      - name: check3
        run: sudo which make
      - name: check4
        run: sudo cat /etc/os-release
      - name: check1
        run: sudo which golangci-lint
      - name: Lint
        run: sudo make lint
      - name: Test
        run: sudo make test
